AllCops:
  Includes:
    - Rakefile
    - config.ru
    - '**/Gemfile'
  Excludes:
    - 'node_modules/**/*'
    - db/**/*
    - config/**/*
    - script/**
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - lib/tasks/*.rake
