require 'rails_helper'

RSpec.feature 'Creative Input', type: :feature, js: true do
  before do
    visit('/')
    @user = FactoryGirl.create(:user)
    network = Network.create(name: 'Comedy Central', abbrev: 'CCL')
    Program.create(name: 'Clusterfest', abbrev: 'CLTF', network_id: network.id)
    Season.create!(name: 'S00', abbrev: 'S00')
    CampaignType.create!(name: 'Binge', abbrev: 'BG')
    BuyMethod.create!(name: 'CPA', abbrev: 'CPA')
    Publisher.create!(name: 'ABC', abbrev: 'ABCX')
    InventoryType.create!(name: 'Partner Social Distribution', abbrev: 'PSD')
    Tactic.create!(name: 'Audio', abbrev: 'AUD')
    Device.create!(name: 'Over the Top', abbrev: 'OTT')
    AdType.create!(name: 'Animated Gif', abbrev: 'GIF')
    TargetingType.create!(name: 'Behavioral', abbrev: 'BT')
    TargetingType.create!(name: 'None', abbrev: 'XX')
    Episode.create!(name: 'E01', abbrev: 'E01')
    Episode.create!(name: 'E02', abbrev: 'E02')
    CreativeGroup.create!(name: 'Always On', abbrev: 'AON')
    CreativeMessage.create!(name: 'Coming Soon', abbrev: 'CS')
    CreativeMessage.create!(name: 'For Your Consideration', abbrev: 'FC')
    AbtestLabel.create!(name: 'Copy', abbrev: 'CP')
    VideoLength.create!(name: '05s')
  end

  it 'creates a creative input' do
    date = Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s + '-' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s
    fill_in('email-login', with: @user.email)
    fill_in('password-login', with: @user.password)
    click_on('Log In')
    click_on('New Campaign')
    expect(page).to have_select('Network', options: ['Select Network', 'Comedy Central'])
    select('Comedy Central', from: 'Network')
    expect(page).to have_text('Comedy Central')
    expect(page).to have_select('Program', options: ['Select Program', 'Clusterfest'])
    select('Clusterfest', from: 'Program')
    expect(page).to have_text('Clusterfest')
    expect(page).to have_select('Season', options: ['Select Season', 'S00'])
    select('S00', from: 'Season')
    expect(page).to have_text('S00')
    expect(page).to have_select('Campaign Type', options: ['Select Campaign Type', 'Binge'])
    select('Binge', from: 'Campaign Type')
    expect(page).to have_text('Binge')
    expect(page).to have_field('customCampaign')
    fill_in('customCampaign', with: 'XX')
    expect(page).to have_text('Create Campaign')
    click_on('Create Campaign')
    expect(page).to have_text("CCL_CLTF_S00_BG_XX_#{date}")
    expect(page).to have_text('New Package')
    click_on('New Package')
    expect(page).to have_select('Publisher', options: ['Select Publisher', 'ABC'])
    select('ABC', from: 'Publisher')
    expect(page).to have_select('Buy Method', options: ['Select Buy Method', 'CPA'])
    select('CPA', from: 'Buy Method')
    expect(page).to have_field('customPackage')
    fill_in('customPackage', with: 'XX')
    expect(page).to have_select('Inventory Type', options: ['Select Inventory Type', 'Partner Social Distribution'])
    select('Partner Social Distribution', from: 'Inventory Type')
    expect(page).to have_text('Create Package')
    click_on('Create Package')
    expect(page).to have_text('CCL_CLTF_S00_SC_ABCX_CPA_PSD_XX')
    expect(page).to have_text('New Placement')
    click_on('New Placement')
    expect(page).to have_select('Episode Start', options: ['Select Episode Start', 'E01', 'E02'])
    select('E01', from: 'Episode Start')
    expect(page).to have_select('Episode End', options: ['Select Episode End', 'E01', 'E02'])
    select('E02', from: 'Episode End')
    expect(page).to have_select('Tactic', options: ['Select Tactic', 'Audio'])
    select('Audio', from: 'Tactic')
    expect(page).to have_select('Device', options: ['Select Device', 'Over the Top'])
    select('Over the Top', from: 'Device')
    expect(page).to have_select('Ad Type', options: ['Select Ad Type', 'Animated Gif'])
    select('Animated Gif', from: 'Ad Type')
    expect(page).to have_field('customAudience')
    fill_in('customAudience', with: 'LA')
    expect(page).to have_field('customWidth')
    fill_in('customWidth', with: '100')
    expect(page).to have_field('customHeight')
    fill_in('customHeight', with: '300')
    expect(page).to have_select('Targeting Type 1', options: ['Select Targeting Type 1', 'Behavioral', 'None'])
    select('Behavioral', from: 'Targeting Type 1')
    click_on('Create Placement')
    expect(page).to have_text('CCL_CLTF_S00_E01-E02_SC_AUD_OTT_ABCX_CPA_GIF_BT-XX-XX-XX_LA_100x300_' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s + '-' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s)
    expect(page).to have_text('New Ad')
    click_on('New Ad')
    expect(page).to have_select('Creative Group', options: ['Select Creative Group', 'Always On'])
    expect(page).to have_field('customAd')
    fill_in('customAd', with: 'X')
    select('Always On', from: 'Creative Group')
    click_on('Create Ad')
    expect(page).to have_text('CCL_CLTF_S00_AON_ABCX_100x300_X')
    expect(page).to have_text('New Creative')
    click_on('New Creative')
    expect(page).to have_select('Creative Message', options: ['Select Creative Message', 'Coming Soon',
                                                              'For Your Consideration'])
    select('Coming Soon', from: 'Creative Message')
    expect(page).to have_field('creativeCustom')
    fill_in('creativeCustom', with: 'President')
    select('01', from: 'Creative Version Number')
    select('Copy', from: 'A/B Test Label')
    click_on('Create Creative')
    expect(page).to have_text('CCL_CLTF_S00_AON_CS_President_01_CP_100x300_' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s + '-' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s)
  end

  it 'clears a creative input' do
    date = Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s + '-' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s
    fill_in('email-login', with: @user.email)
    fill_in('password-login', with: @user.password)
    click_on('Log In')
    click_on('New Campaign')
    expect(page).to have_select('Network', options: ['Select Network', 'Comedy Central'])
    select('Comedy Central', from: 'Network')
    expect(page).to have_text('Comedy Central')
    expect(page).to have_select('Program', options: ['Select Program', 'Clusterfest'])
    select('Clusterfest', from: 'Program')
    expect(page).to have_text('Clusterfest')
    expect(page).to have_select('Season', options: ['Select Season', 'S00'])
    select('S00', from: 'Season')
    expect(page).to have_text('S00')
    expect(page).to have_select('Campaign Type', options: ['Select Campaign Type', 'Binge'])
    select('Binge', from: 'Campaign Type')
    expect(page).to have_text('Binge')
    expect(page).to have_field('customCampaign')
    fill_in('customCampaign', with: 'XX')
    expect(page).to have_text('Create Campaign')
    click_on('Create Campaign')
    expect(page).to have_text("CCL_CLTF_S00_BG_XX_#{date}")
    expect(page).to have_text('New Package')
    click_on('New Package')
    expect(page).to have_select('Publisher', options: ['Select Publisher', 'ABC'])
    select('ABC', from: 'Publisher')
    expect(page).to have_select('Buy Method', options: ['Select Buy Method', 'CPA'])
    select('CPA', from: 'Buy Method')
    expect(page).to have_field('customPackage')
    fill_in('customPackage', with: 'XX')
    expect(page).to have_select('Inventory Type', options: ['Select Inventory Type', 'Partner Social Distribution'])
    select('Partner Social Distribution', from: 'Inventory Type')
    expect(page).to have_text('Create Package')
    click_on('Create Package')
    expect(page).to have_text('CCL_CLTF_S00_SC_ABCX_CPA_PSD_XX')
    expect(page).to have_text('New Placement')
    click_on('New Placement')
    expect(page).to have_select('Episode Start', options: ['Select Episode Start', 'E01', 'E02'])
    select('E01', from: 'Episode Start')
    expect(page).to have_select('Episode End', options: ['Select Episode End', 'E01', 'E02'])
    select('E02', from: 'Episode End')
    expect(page).to have_select('Tactic', options: ['Select Tactic', 'Audio'])
    select('Audio', from: 'Tactic')
    expect(page).to have_select('Device', options: ['Select Device', 'Over the Top'])
    select('Over the Top', from: 'Device')
    expect(page).to have_select('Ad Type', options: ['Select Ad Type', 'Animated Gif'])
    select('Animated Gif', from: 'Ad Type')
    expect(page).to have_field('customAudience')
    fill_in('customAudience', with: 'LA')
    expect(page).to have_field('customWidth')
    fill_in('customWidth', with: '100')
    expect(page).to have_field('customHeight')
    fill_in('customHeight', with: '300')
    expect(page).to have_select('Targeting Type 1', options: ['Select Targeting Type 1', 'Behavioral', 'None'])
    select('Behavioral', from: 'Targeting Type 1')
    click_on('Create Placement')
    expect(page).to have_text('CCL_CLTF_S00_E01-E02_SC_AUD_OTT_ABCX_CPA_GIF_BT-XX-XX-XX_LA_100x300_' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s + '-' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s)
    expect(page).to have_text('New Ad')
    click_on('New Ad')
    expect(page).to have_select('Creative Group', options: ['Select Creative Group', 'Always On'])
    expect(page).to have_field('customAd')
    fill_in('customAd', with: 'X')
    select('Always On', from: 'Creative Group')
    click_on('Create Ad')
    expect(page).to have_text('CCL_CLTF_S00_AON_ABCX_100x300_X')
    expect(page).to have_text('New Creative')
    click_on('New Creative')
    expect(page).to have_select('Creative Message', options: ['Select Creative Message', 'Coming Soon',
                                                              'For Your Consideration'])
    select('Coming Soon', from: 'Creative Message')
    expect(page).to have_field('creativeCustom')
    fill_in('creativeCustom', with: 'President')
    select('01', from: 'Creative Version Number')
    select('Copy', from: 'A/B Test Label')
    click_on('Cancel Creative')
    expect(page).to_not have_text('CCL_CLTF_S00_AON_CS_President_01_CP_100x300_0101-0202')
  end

  it 'edits a creative input' do 
    date = Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s + '-' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s
    fill_in('email-login', with: @user.email)
    fill_in('password-login', with: @user.password)
    click_on('Log In')
    click_on('New Campaign')
    expect(page).to have_select('Network', options: ['Select Network', 'Comedy Central'])
    select('Comedy Central', from: 'Network')
    expect(page).to have_text('Comedy Central')
    expect(page).to have_select('Program', options: ['Select Program', 'Clusterfest'])
    select('Clusterfest', from: 'Program')
    expect(page).to have_text('Clusterfest')
    expect(page).to have_select('Season', options: ['Select Season', 'S00'])
    select('S00', from: 'Season')
    expect(page).to have_text('S00')
    expect(page).to have_select('Campaign Type', options: ['Select Campaign Type', 'Binge'])
    select('Binge', from: 'Campaign Type')
    expect(page).to have_text('Binge')
    expect(page).to have_field('customCampaign')
    fill_in('customCampaign', with: 'XX')
    expect(page).to have_text('Create Campaign')
    click_on('Create Campaign')
    expect(page).to have_text("CCL_CLTF_S00_BG_XX_#{date}")
    expect(page).to have_text('New Package')
    click_on('New Package')
    expect(page).to have_select('Publisher', options: ['Select Publisher', 'ABC'])
    select('ABC', from: 'Publisher')
    expect(page).to have_select('Buy Method', options: ['Select Buy Method', 'CPA'])
    select('CPA', from: 'Buy Method')
    expect(page).to have_field('customPackage')
    fill_in('customPackage', with: 'XX')
    expect(page).to have_select('Inventory Type', options: ['Select Inventory Type', 'Partner Social Distribution'])
    select('Partner Social Distribution', from: 'Inventory Type')
    expect(page).to have_text('Create Package')
    click_on('Create Package')
    expect(page).to have_text('CCL_CLTF_S00_SC_ABCX_CPA_PSD_XX')
    expect(page).to have_text('New Placement')
    click_on('New Placement')
    expect(page).to have_select('Episode Start', options: ['Select Episode Start', 'E01', 'E02'])
    select('E01', from: 'Episode Start')
    expect(page).to have_select('Episode End', options: ['Select Episode End', 'E01', 'E02'])
    select('E02', from: 'Episode End')
    expect(page).to have_select('Tactic', options: ['Select Tactic', 'Audio'])
    select('Audio', from: 'Tactic')
    expect(page).to have_select('Device', options: ['Select Device', 'Over the Top'])
    select('Over the Top', from: 'Device')
    expect(page).to have_select('Ad Type', options: ['Select Ad Type', 'Animated Gif'])
    select('Animated Gif', from: 'Ad Type')
    expect(page).to have_field('customAudience')
    fill_in('customAudience', with: 'LA')
    expect(page).to have_field('customWidth')
    fill_in('customWidth', with: '100')
    expect(page).to have_field('customHeight')
    fill_in('customHeight', with: '300')
    expect(page).to have_select('Targeting Type 1', options: ['Select Targeting Type 1', 'Behavioral', 'None'])
    select('Behavioral', from: 'Targeting Type 1')
    click_on('Create Placement')
    expect(page).to have_text('CCL_CLTF_S00_E01-E02_SC_AUD_OTT_ABCX_CPA_GIF_BT-XX-XX-XX_LA_100x300_' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s + '-' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s)
    expect(page).to have_text('New Ad')
    click_on('New Ad')
    expect(page).to have_select('Creative Group', options: ['Select Creative Group', 'Always On'])
    expect(page).to have_field('customAd')
    fill_in('customAd', with: 'X')
    select('Always On', from: 'Creative Group')
    click_on('Create Ad')
    expect(page).to have_text('CCL_CLTF_S00_AON_ABCX_100x300_X')
    expect(page).to have_text('New Creative')
    click_on('New Creative')
    expect(page).to have_select('Creative Message', options: ['Select Creative Message', 'Coming Soon',
                                                              'For Your Consideration'])
    select('Coming Soon', from: 'Creative Message')
    expect(page).to have_field('creativeCustom')
    fill_in('creativeCustom', with: 'President')
    select('01', from: 'Creative Version Number')
    select('Copy', from: 'A/B Test Label')
    click_on('Create Creative')
    expect(page).to have_text('CCL_CLTF_S00_AON_CS_President_01_CP_100x300_' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s + '-' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s)
    click_on('Edit')
    select('For Your Consideration', from: 'Creative Message')
    expect(page).to have_text('Update Creative')
    click_on('Update Creative')
    expect(page).to have_text('CCL_CLTF_S00_AON_FC_President_01_CP_100x300_' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s + '-' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s)
  end 

  it 'copies a creative input' do
    date = Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s + '-' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s
    fill_in('email-login', with: @user.email)
    fill_in('password-login', with: @user.password)
    click_on('Log In')
    click_on('New Campaign')
    expect(page).to have_select('Network', options: ['Select Network', 'Comedy Central'])
    select('Comedy Central', from: 'Network')
    expect(page).to have_text('Comedy Central')
    expect(page).to have_select('Program', options: ['Select Program', 'Clusterfest'])
    select('Clusterfest', from: 'Program')
    expect(page).to have_text('Clusterfest')
    expect(page).to have_select('Season', options: ['Select Season', 'S00'])
    select('S00', from: 'Season')
    expect(page).to have_text('S00')
    expect(page).to have_select('Campaign Type', options: ['Select Campaign Type', 'Binge'])
    select('Binge', from: 'Campaign Type')
    expect(page).to have_text('Binge')
    expect(page).to have_field('customCampaign')
    fill_in('customCampaign', with: 'XX')
    expect(page).to have_text('Create Campaign')
    click_on('Create Campaign')
    expect(page).to have_text("CCL_CLTF_S00_BG_XX_#{date}")
    expect(page).to have_text('New Package')
    click_on('New Package')
    expect(page).to have_select('Publisher', options: ['Select Publisher', 'ABC'])
    select('ABC', from: 'Publisher')
    expect(page).to have_select('Buy Method', options: ['Select Buy Method', 'CPA'])
    select('CPA', from: 'Buy Method')
    expect(page).to have_field('customPackage')
    fill_in('customPackage', with: 'XX')
    expect(page).to have_select('Inventory Type', options: ['Select Inventory Type', 'Partner Social Distribution'])
    select('Partner Social Distribution', from: 'Inventory Type')
    expect(page).to have_text('Create Package')
    click_on('Create Package')
    expect(page).to have_text('CCL_CLTF_S00_SC_ABCX_CPA_PSD_XX')
    expect(page).to have_text('New Placement')
    click_on('New Placement')
    expect(page).to have_select('Episode Start', options: ['Select Episode Start', 'E01', 'E02'])
    select('E01', from: 'Episode Start')
    expect(page).to have_select('Episode End', options: ['Select Episode End', 'E01', 'E02'])
    select('E02', from: 'Episode End')
    expect(page).to have_select('Tactic', options: ['Select Tactic', 'Audio'])
    select('Audio', from: 'Tactic')
    expect(page).to have_select('Device', options: ['Select Device', 'Over the Top'])
    select('Over the Top', from: 'Device')
    expect(page).to have_select('Ad Type', options: ['Select Ad Type', 'Animated Gif'])
    select('Animated Gif', from: 'Ad Type')
    expect(page).to have_field('customAudience')
    fill_in('customAudience', with: 'LA')
    expect(page).to have_field('customWidth')
    fill_in('customWidth', with: '100')
    expect(page).to have_field('customHeight')
    fill_in('customHeight', with: '300')
    expect(page).to have_select('Targeting Type 1', options: ['Select Targeting Type 1', 'Behavioral', 'None'])
    select('Behavioral', from: 'Targeting Type 1')
    click_on('Create Placement')
    expect(page).to have_text('CCL_CLTF_S00_E01-E02_SC_AUD_OTT_ABCX_CPA_GIF_BT-XX-XX-XX_LA_100x300_' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s + '-' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s)
    expect(page).to have_text('New Ad')
    click_on('New Ad')
    expect(page).to have_select('Creative Group', options: ['Select Creative Group', 'Always On'])
    expect(page).to have_field('customAd')
    fill_in('customAd', with: 'X')
    select('Always On', from: 'Creative Group')
    click_on('Create Ad')
    expect(page).to have_text('CCL_CLTF_S00_AON_ABCX_100x300_X')
    expect(page).to have_text('New Creative')
    click_on('New Creative')
    expect(page).to have_select('Creative Message', options: ['Select Creative Message', 'Coming Soon',
                                                              'For Your Consideration'])
    select('Coming Soon', from: 'Creative Message')
    expect(page).to have_field('creativeCustom')
    fill_in('creativeCustom', with: 'President')
    select('01', from: 'Creative Version Number')
    select('Copy', from: 'A/B Test Label')
    click_on('Create Creative')
    expect(page).to have_text('CCL_CLTF_S00_AON_CS_President_01_CP_100x300_' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s + '-' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s)
    click_on('Copy/Create')
    select('For Your Consideration', from: 'Creative Message')
    click_on('Create Creative')
    expect(page).to have_text('CCL_CLTF_S00_AON_FC_President_01_CP_100x300_' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s + '-' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s)
  end

  it 'deletes a creative input' do 
    date = Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s + '-' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s
    fill_in('email-login', with: @user.email)
    fill_in('password-login', with: @user.password)
    click_on('Log In')
    click_on('New Campaign')
    expect(page).to have_select('Network', options: ['Select Network', 'Comedy Central'])
    select('Comedy Central', from: 'Network')
    expect(page).to have_text('Comedy Central')
    expect(page).to have_select('Program', options: ['Select Program', 'Clusterfest'])
    select('Clusterfest', from: 'Program')
    expect(page).to have_text('Clusterfest')
    expect(page).to have_select('Season', options: ['Select Season', 'S00'])
    select('S00', from: 'Season')
    expect(page).to have_text('S00')
    expect(page).to have_select('Campaign Type', options: ['Select Campaign Type', 'Binge'])
    select('Binge', from: 'Campaign Type')
    expect(page).to have_text('Binge')
    expect(page).to have_field('customCampaign')
    fill_in('customCampaign', with: 'XX')
    expect(page).to have_text('Create Campaign')
    click_on('Create Campaign')
    expect(page).to have_text("CCL_CLTF_S00_BG_XX_#{date}")
    expect(page).to have_text('New Package')
    click_on('New Package')
    expect(page).to have_select('Publisher', options: ['Select Publisher', 'ABC'])
    select('ABC', from: 'Publisher')
    expect(page).to have_select('Buy Method', options: ['Select Buy Method', 'CPA'])
    select('CPA', from: 'Buy Method')
    expect(page).to have_field('customPackage')
    fill_in('customPackage', with: 'XX')
    expect(page).to have_select('Inventory Type', options: ['Select Inventory Type', 'Partner Social Distribution'])
    select('Partner Social Distribution', from: 'Inventory Type')
    expect(page).to have_text('Create Package')
    click_on('Create Package')
    expect(page).to have_text('CCL_CLTF_S00_SC_ABCX_CPA_PSD_XX')
    expect(page).to have_text('New Placement')
    click_on('New Placement')
    expect(page).to have_select('Episode Start', options: ['Select Episode Start', 'E01', 'E02'])
    select('E01', from: 'Episode Start')
    expect(page).to have_select('Episode End', options: ['Select Episode End', 'E01', 'E02'])
    select('E02', from: 'Episode End')
    expect(page).to have_select('Tactic', options: ['Select Tactic', 'Audio'])
    select('Audio', from: 'Tactic')
    expect(page).to have_select('Device', options: ['Select Device', 'Over the Top'])
    select('Over the Top', from: 'Device')
    expect(page).to have_select('Ad Type', options: ['Select Ad Type', 'Animated Gif'])
    select('Animated Gif', from: 'Ad Type')
    expect(page).to have_field('customAudience')
    fill_in('customAudience', with: 'LA')
    expect(page).to have_field('customWidth')
    fill_in('customWidth', with: '100')
    expect(page).to have_field('customHeight')
    fill_in('customHeight', with: '300')
    expect(page).to have_select('Targeting Type 1', options: ['Select Targeting Type 1', 'Behavioral', 'None'])
    select('Behavioral', from: 'Targeting Type 1')
    click_on('Create Placement')
    expect(page).to have_text('CCL_CLTF_S00_E01-E02_SC_AUD_OTT_ABCX_CPA_GIF_BT-XX-XX-XX_LA_100x300_' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s + '-' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s)
    expect(page).to have_text('New Ad')
    click_on('New Ad')
    expect(page).to have_select('Creative Group', options: ['Select Creative Group', 'Always On'])
    expect(page).to have_field('customAd')
    fill_in('customAd', with: 'X')
    select('Always On', from: 'Creative Group')
    click_on('Create Ad')
    expect(page).to have_text('CCL_CLTF_S00_AON_ABCX_100x300_X')
    expect(page).to have_text('New Creative')
    click_on('New Creative')
    expect(page).to have_select('Creative Message', options: ['Select Creative Message', 'Coming Soon',
                                                              'For Your Consideration'])
    select('Coming Soon', from: 'Creative Message')
    expect(page).to have_field('creativeCustom')
    fill_in('creativeCustom', with: 'President')
    select('01', from: 'Creative Version Number')
    select('Copy', from: 'A/B Test Label')
    click_on('Create Creative')
    expect(page).to have_text('CCL_CLTF_S00_AON_CS_President_01_CP_100x300_' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s + '-' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s)
    click_on('Delete')
    click_on('Yes')
    expect(page).to_not have_text('CCL_CLTF_S00_AON_CS_President_01_CP_100x300_' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s + '-' + Time.now.strftime('%Y').to_s + Time.now.strftime('%m').to_s + Time.now.strftime('%d').to_s)
  end 
  
end
